# Generated by Django 3.1.1 on 2020-09-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='units',
            new_name='dimension',
        ),
    ]
